apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: role-serviceaccount
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
